apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone-site
  strategy:
    type: RollingUpdate
    rollingUpdate:
      #maxSurge: 25%
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: capstone-site
    spec:
      containers:
      - name: capstone-site
        image: alexcgdocker/my-capstone-site:1.2
        ports:
        - containerPort: 80
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: capstone-site
#spec:
#  type: LoadBalancer
#  selector:
#    app: capstone-site
#  ports:
#    - port: 8000
#      targetPort: 80
#      protocol: TCP

apiVersion: v1
kind: Service
metadata:
  name: capstone-site
spec:
  type: NodePort
  selector:
    app: capstone-site
  ports:
    - port: 8000
      targetPort: 80
      protocol: TCP
      nodePort: 30100
